# Generated by Django 3.2.8 on 2022-02-19 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_alter_accountuser_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('id_image', models.UUIDField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.accountuser')),
            ],
        ),
    ]
