# Generated by Django 3.2.8 on 2021-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.UUIDField()),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
