# Generated by Django 3.2.8 on 2021-10-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.UUIDField()),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
