# Generated by Django 3.2.8 on 2021-10-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211027_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
